os: linux
dist: bionic
language: python
install: pip install -U tox pip virtualenv
script:
  - tox
notifications:
  email: false
cache: pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - graphviz
      - pandoc
jobs:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.8"
      script:
        - git clone https://github.com/Qiskit/qiskit-tutorials
        - python -m pip install --upgrade pip setuptools wheel virtualenv
        - virtualenv /tmp/docs_build
        - source /tmp/docs_build/bin/activate
        - pip install -U jupyter sphinx nbsphinx sphinx_rtd_theme qiskit-terra[visualization] cvxpy
        - pip install -U .
        - sudo apt-get install -y pandoc graphviz
        - cd qiskit-tutorials
        - sphinx-build -b html . _build/html
    - if: branch = master AND type = push
      python: "3.7"
      script: travis_wait 50 tools/deploy_documentation.sh
      git:
        depth: false
    - if: branch = master AND type = push
      python: "3.7"
      script: travis_wait 50 tools/deploy_translatable_strings.sh
      git:
        depth: false
    - if: tag IS present
      python: "3.7"
      env:
        - TWINE_USERNAME=qiskit
      install: pip install -U twine
      script:
        - python3 setup.py sdist
        - twine upload dist/qiskit*tar.gz
