cache: pip
sudo: false
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-4.8
#      - g++-4.8
jobs:
  include:
    - if: commit_message =~ /^[doc]/
      python: "3.5"
      install:
        - pip install qiskit-terra qiskit-aer qiskit-aqua qiskit-chemistry
        - pip install -r requirements-dev.txt
      script: tools/deploy_documentation.sh
#    - python: "3.6"
#      env: TOXENV=py36
#    - os: linux
#      dist: xenial
#      python: 3.7
#      env: TOXENV=py37
#      sudo: true
#    - python: "3.5"
#      env: TOXENV=lint
language: python
install: pip install -U tox
script:
  - tox

notifications:
  email: false
